language: node_js
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: f8EUQSIq533/UwOkMWznPJGPO+Fa3Um7fq7cgmH7rrAcMpWgDi53YptOIybzAhVu2FqNiKxLdL+iqY+U0qX2IWfwkG7bE/1gk4uKEafxu2C/Gsu9AStzWYIjzjXeD37fm1NhCuyQyTnYc7d47taA/zil7/SAnaH86sLZB/H31uocfgvHFjcySvRUBHFEeZ8HYucueegARSyF90vHrmMVgKb3F0mg5IeRFYVxjWLzaDbO1fcj6Jy6w9z0id+8WXzyIogk5/T6AEphRQykHv3HxyNbZeep0PelzXTgDb4prrXn/FOpp2C/lT2/AtmjgHVKsT8sNdEosSSm2sz5McOlX1huRx6pT/EFDJze8MvrHBVnkGE5CUluasytoJbIqmxY1qS4V7NL7UX34fWsH4arSqlmnunR4hUnST3BpQitOyXHmoWauzM/mOwUCiVB5Cm2WZs1G8nyurC/0znOrrYBCFDGLZb4lNHK2UlW4XH1nwq9YlA/0bZR+8uxdTgmvsXtbxfl/WJ4ib5YakuqzNmdE7PTo7CqGuH/78qOgU7aWjDG6uSIM7k1R1dutJSp6gBpmQ6Nc4R35+evn0p6RoFFtq+9c6/y9w9fBPb0mTzAG4t00TWqIEUkYmKkd9EUoxoC04TRATMiiU6LQlEFqcUaQn5CeVzTjgewx9XMgWX4lUQ=
  file:
    - 'svg-element-attributes.js'
    - 'svg-element-attributes.min.js'
  on:
    tags: true
