language: node_js
node_js:
- lts/boron
- node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: FZw+HLVgzfWr1r6PH9oRN3yTXU3rPuPzhaE0a3gJa8k/NmQIeGSa/x+zRXpyYJjNk/tMTxeh5XCgszbWbtOOUaHdtOMNeoEnrdYk49bbY9qU5Y77ZUrJFhnbg6XnDLnMTqwGuLOJ+9J5sTeuWIV+JPNbsAqVVsbOOr+YKKPpinekhEU3jvIYECJHKQ9MbjyXpzRFsSCLdZvBqcsRShfgccb9cAye2BGs4aPCpSYMRtXBn0QAOqXu7dTTnDcdvVwvVVvKif08FbpqpwOwXTrHk+kZVSaTfTEVNIteRkQ1RnNQlSE0vG6qHwstY+FvFFsmENveUfqAuqIhpjHn05lkrWoeQR71t4NCBPn9WJWNfUfoxmedVxoDG/2mPPhLZonrciGhQsm2CQYcMz0pwEY0GE6tgcTEQTZOGBM4btCcbn8BrFrscvDyc5CBMiUJtVbGqh94oQmghiqY2z1k9P8kNGlTUpHlmQHBelkb6ZSOOCLnKk1fy1N/GXU7PQXWD9lZSLIHc+HYRYs925sFKPi8qQffBYvNiyg1CCQH/KoMlZdQy3aahJyolu/6DLELacBSy05TVO2JSzZsSKciTQ+PLD50IZ9vQQ9pxsvKdrHtgKaBMxBzus97+JGH9MUod4VqyZPTkZnxtRk2ZzCnrmhjYe1pcsSgXECu3lHeDE9SL4I=
  file:
    - "svg-element-attributes.js"
    - "svg-element-attributes.min.js"
  on:
    tags: true
